name: Sync Fork

on:
  schedule:
    - cron: '* * * * *' # every 30 minutes

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: crocodilestick
          base: main
          head: main
