name: Sync Fork

on:
  schedule:
    - cron: '0 12 1 * *' # on the 1st of every month
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: crocodilestick
          base: main
          head: main
          ignore_fail: true
